version: 3

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev:/var/lib/postgresql/data
    env_file:
      - stack.env
      
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"
    env_file:
      - stack.env
      
